telegram_bot:
  enable: true
  api: TELEGRAM_PRINTER_API_KEY
  image_dir: received_images/
  allowed_users:
  #environment variables of allowed telegram users
    - CHAT_ID_USER1
printer:
  enable: true
  image_width: 384
  idVendor: 0x6868
  idProduct: 0x0200
  profile: "Sunmi-V2"
